In [2]:
import numpy as np

1. Завантажити набір даних за допомогою load_iris() бібліотеки sklearn.

In [1]:
from sklearn.datasets import load_iris

# Завантаження даних Iris
iris_data = load_iris()

# Отримання ознак та міток класів
features = iris_data.data
labels = iris_data.target

# Виведення перших декількох рядків даних
print("Перші п'ять рядків даних:")
print(features[:5])
print("Мітки класів:")
print(labels[:5])

Перші п'ять рядків даних:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
Мітки класів:
[0 0 0 0 0]


2. Розподілити дані на навчальні та для тестування за допомогою train_test_split() бібліотеки sklearn.

In [3]:
from sklearn.model_selection import train_test_split

# Розбиття на тренувальний та тестовий набір
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, test_size=0.2, random_state=42)

# Виведення розмірності тренувального та тестового наборів
print("Розмірність тренувального набору:", features_train.shape)
print("Розмірність тестового набору:", features_test.shape)

Розмірність тренувального набору: (120, 4)
Розмірність тестового набору: (30, 4)


3. Використати вибірку ознак окремо для кожного класа.

In [4]:
import pandas as pd

# Створення датафрейму для ознак тренувального набору
features_train_df = pd.DataFrame(features_train, columns=[f'feature_{i}' for i in range(features_train.shape[1])])

# Створення датафрейму для міток класів тренувального набору
labels_train_df = pd.DataFrame(labels_train, columns=['label'])

# Виведення перших декількох рядків кожного датафрейму для перевірки
print("Датафрейм ознак:")
print(features_train_df.head())

print("\nДатафрейм міток класів:")
print(labels_train_df.head())


Датафрейм ознак:
   feature_0  feature_1  feature_2  feature_3
0        4.6        3.6        1.0        0.2
1        5.7        4.4        1.5        0.4
2        6.7        3.1        4.4        1.4
3        4.8        3.4        1.6        0.2
4        4.4        3.2        1.3        0.2

Датафрейм міток класів:
   label
0      0
1      0
2      1
3      0
4      0


In [5]:
# Об'єднання датафреймів ознак та міток
train_df = pd.concat([features_train_df, labels_train_df], axis=1)

# Виведення перших декількох рядків об'єднаного датафрейму для перевірки
print("Об'єднаний датафрейм:")
print(train_df.head())

Об'єднаний датафрейм:
   feature_0  feature_1  feature_2  feature_3  label
0        4.6        3.6        1.0        0.2      0
1        5.7        4.4        1.5        0.4      0
2        6.7        3.1        4.4        1.4      1
3        4.8        3.4        1.6        0.2      0
4        4.4        3.2        1.3        0.2      0


In [6]:
# Відфільтрування датафрейму за класом 0
filtered_class_0 = train_df[train_df['label'] == 0]

# Відфільтрування датафрейму за класом 1
filtered_class_1 = train_df[train_df['label'] == 1]

# Відфільтрування датафрейму за класом 2
filtered_class_2 = train_df[train_df['label'] == 2]

# Виведення перших декількох рядків кожного відфільтрованого датафрейму для перевірки
print("Відфільтрований датафрейм для класу 0:")
print(filtered_class_0.head())

print("\nВідфільтрований датафрейм для класу 1:")
print(filtered_class_1.head())

print("\nВідфільтрований датафрейм для класу 2:")
print(filtered_class_2.head())


Відфільтрований датафрейм для класу 0:
   feature_0  feature_1  feature_2  feature_3  label
0        4.6        3.6        1.0        0.2      0
1        5.7        4.4        1.5        0.4      0
3        4.8        3.4        1.6        0.2      0
4        4.4        3.2        1.3        0.2      0
7        5.2        3.5        1.5        0.2      0

Відфільтрований датафрейм для класу 1:
    feature_0  feature_1  feature_2  feature_3  label
2         6.7        3.1        4.4        1.4      1
6         6.4        3.2        4.5        1.5      1
11        6.0        3.4        4.5        1.6      1
12        6.7        3.1        4.7        1.5      1
15        5.5        2.4        3.7        1.0      1

Відфільтрований датафрейм для класу 2:
    feature_0  feature_1  feature_2  feature_3  label
5         6.3        2.5        5.0        1.9      2
10        5.8        2.7        5.1        1.9      2
16        6.3        2.8        5.1        1.5      2
17        6.4        3.

4. Реалізувати розрахунок матриць коваріації для набору ознак кожного класа.

In [7]:
from numpy.linalg import inv
x_0 = np.array(filtered_class_0[['feature_0', 'feature_1', 'feature_2', 'feature_3']])
np.shape(x_0)

(40, 4)

In [8]:
x_1 = np.array(filtered_class_1[['feature_0', 'feature_1', 'feature_2', 'feature_3']])
np.shape(x_1)

(41, 4)

In [9]:
x_2 = np.array(filtered_class_2[['feature_0', 'feature_1', 'feature_2', 'feature_3']])
np.shape(x_2)

(39, 4)

In [10]:
x_0_cov = np.cov(x_0.transpose())
np.shape(x_0_cov)

(4, 4)

In [11]:
x_1_cov = np.cov(x_1.transpose())
np.shape(x_1_cov)

(4, 4)

In [12]:
x_2_cov = np.cov(x_2.transpose())
np.shape(x_2_cov)

(4, 4)

5. Реалізувати розрахунок обернених матриць коваріації.

In [13]:
inv_cov_0 = inv(x_0_cov)
np.shape(inv_cov_0)

(4, 4)

In [14]:
inv_cov_1 = inv(x_1_cov)
np.shape(inv_cov_1)

(4, 4)

In [15]:
inv_cov_2 = inv(x_2_cov)
np.shape(inv_cov_2)

(4, 4)

6. Обчислити апріорні імовірності кожного класа у тренувальних даних.

In [16]:
P_0 = len(train_df[train_df['label'] == 0])/len(train_df)
P_0

0.3333333333333333

In [17]:
P_1 = len(train_df[train_df['label'] == 0])/len(train_df)
P_1

0.3333333333333333

In [18]:
P_2 = len(train_df[train_df['label'] == 0])/len(train_df)
P_2

0.3333333333333333

7. Реалізувати функцію обчислення значень дискримінантної функції для одного рядка (вектора) тестових даних.

In [19]:
def g(x_test, X_class, X_cov, X_inv_cov, X_prob):
    """Повертає значення дискримінантної функції для вектора даних

    Parameters
    ----------
    x_test : вектор тестових даних
             Array of samples/test vectors.
    X_class:

    Returns
    -------
    C : ndarray of shape (n_samples, n_classes)
        Posterior log-probabilities of classification per class.
    """
    cov_det = np.linalg.det(X_cov)
    log_cov_det = np.log(cov_det)
    x_mean = np.reshape(np.mean(X_class, axis=0), (np.shape(X_class)[1],1))
    diff = x_test.reshape(-1,1) - x_mean
    dif_cov = np.dot(diff.transpose(), X_inv_cov)
    diff_res = np.dot(dif_cov, diff)

    g_i = -1/2*diff_res - 1/2*log_cov_det+np.log(X_prob)
    return g_i

In [20]:
def g_matrix(X_test, X_class, X_cov, X_inv_cov, X_prob):

    g_val = []
    g_proba = []

    for i in range(len(X_test)):
        x_test = X_test[i]
        g_0 = g(x_test, X_class[0], X_cov[0], X_inv_cov[0], X_prob[0])
        g_1 = g(x_test, X_class[1], X_cov[1], X_inv_cov[1], X_prob[1])
        g_2 = g(x_test, X_class[2], X_cov[2], X_inv_cov[2], X_prob[2])
        g_i = np.array(list([g_0[0][0], g_1[0][0], g_2[0][0]]))
        values = g_i.reshape(1,-1)
        likelihood = np.exp(values - values.max(axis=1)[:, np.newaxis])
        res = likelihood / likelihood.sum(axis=1)[:, np.newaxis]

        g_val.append(values)
        g_proba.append(res)

    return np.array(g_val), np.array(g_proba)


8. Реалізувати функцію обчислення значень дискримінантної функції та імовірностей приналежності кожному класу для всієї матриці тестових даних.

In [21]:
g_val, g_proba = g_matrix(features_test, [x_0, x_1, x_2], [x_0_cov, x_1_cov, x_2_cov], [inv_cov_0,inv_cov_1,inv_cov_2], [P_0, P_1, P_2])
print('Значення дискримінантної функції\n', g_val)

print('Значення імовірностей класів\n', g_proba)

Значення дискримінантної функції
 [[[-1.73824135e+02 -2.52281392e-02 -3.49520059e+00]]

 [[ 2.55707053e+00 -6.12696829e+01 -1.48680373e+02]]

 [[-5.46924689e+02 -2.88870057e+01 -7.41688968e+00]]

 [[-1.70239537e+02  3.91961458e+00 -2.29531638e+00]]

 [[-2.03606667e+02  2.44393545e+00 -5.18299462e+00]]

 [[ 2.57782297e+00 -4.54739129e+01 -1.27201698e+02]]

 [[-9.39425715e+01  1.34298380e+00 -1.52924470e+01]]

 [[-3.09419032e+02 -2.37428372e+01 -1.69061220e+00]]

 [[-1.90916129e+02 -3.25645447e+00 -2.86562796e+00]]

 [[-1.10421110e+02  4.01273526e+00 -1.03490484e+01]]

 [[-2.64642461e+02 -3.52953380e+00  1.26175265e+00]]

 [[ 3.73669619e+00 -4.18950151e+01 -1.08919679e+02]]

 [[ 2.16114248e+00 -6.00639686e+01 -1.54170055e+02]]

 [[ 3.57415757e+00 -4.43258910e+01 -1.10808011e+02]]

 [[ 4.70392010e+00 -6.21790319e+01 -1.41708565e+02]]

 [[-1.88933899e+02  2.91365083e+00 -5.52546237e+00]]

 [[-3.62367662e+02 -1.04530319e+01  2.53054669e+00]]

 [[-1.07782690e+02  3.72695745e+00 -7.94444548e+

9. Виконати прогнозування на тестових даних за допомогою функії QuadraticDiscriminantAnalysis() бібліотеки sklearn та порівняти отримані результати.

In [22]:
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

features_train, features_test, labels_train, labels_test

qda = QuadraticDiscriminantAnalysis()
qda.fit(features_train, labels_train)

values_qda = qda._decision_function(features_test)

proba_qda = qda.predict_proba(features_test)

print('Значення дискримінантної функції\n', values_qda)

print('Значення імовірностей класів\n', proba_qda)

Значення дискримінантної функції
 [[-1.73824135e+02 -5.35526638e-04 -3.52051840e+00]
 [ 2.55707053e+00 -6.12449903e+01 -1.48705691e+02]
 [-5.46924689e+02 -2.88623131e+01 -7.44220749e+00]
 [-1.70239537e+02  3.94430719e+00 -2.32063418e+00]
 [-2.03606667e+02  2.46862806e+00 -5.20831243e+00]
 [ 2.57782297e+00 -4.54492202e+01 -1.27227016e+02]
 [-9.39425715e+01  1.36767641e+00 -1.53177648e+01]
 [-3.09419032e+02 -2.37181445e+01 -1.71593000e+00]
 [-1.90916129e+02 -3.23176186e+00 -2.89094576e+00]
 [-1.10421110e+02  4.03742787e+00 -1.03743662e+01]
 [-2.64642461e+02 -3.50484118e+00  1.23643485e+00]
 [ 3.73669619e+00 -4.18703224e+01 -1.08944997e+02]
 [ 2.16114248e+00 -6.00392760e+01 -1.54195372e+02]
 [ 3.57415757e+00 -4.43011984e+01 -1.10833329e+02]
 [ 4.70392010e+00 -6.21543393e+01 -1.41733883e+02]
 [-1.88933899e+02  2.93834345e+00 -5.55078018e+00]
 [-3.62367662e+02 -1.04283392e+01  2.50522888e+00]
 [-1.07782690e+02  3.75165006e+00 -7.96976329e+00]
 [-1.58049248e+02  2.52629544e+00 -2.44928119e+0

In [26]:
own = [np.argmax(i) for i in g_proba]
own

[1,
 0,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0]

In [27]:
sk = [np.argmax(i) for i in proba_qda]
sk

[1,
 0,
 2,
 1,
 1,
 0,
 1,
 2,
 2,
 1,
 2,
 0,
 0,
 0,
 0,
 1,
 2,
 1,
 1,
 2,
 0,
 2,
 0,
 2,
 2,
 2,
 2,
 2,
 0,
 0]

In [28]:
def compare_lists(list1, list2):
    # Convert lists to sets to remove duplicates and enable set operations
    set1 = set(list1)
    set2 = set(list2)

    # Find the intersection of both sets (i.e., common elements)
    common_elements = set1.intersection(set2)

    # Calculate the number of common elements
    num_common = len(common_elements)

    # Calculate the total number of unique elements in both lists
    total_unique = len(set1.union(set2))

    # Calculate the percentage of matching elements
    if total_unique == 0:
        percentage = 0.0
    else:
        percentage = (num_common / total_unique) * 100

    return percentage

compare_lists(own, sk)

100.0

10. Зробити висновок про ступінь схожості результатів, отриманих власною функцією та бібліотекою sklearn.


Прогнозування на тестових даних за допомогою функії QuadraticDiscriminantAnalysis() бібліотеки sklearn та результати, отримані за допомогою матричних операцій, до яких зводяться програмні реалізації розглянутих методів: ідентичні.